### PR TITLE
Update key-bindings.zsh

### PR DESCRIPTION
**Pull request by cesc-park**
For Home key and End key support!

### CODE REVIEW

**Comment by wookayin** [comment]
In my environment, Home and End keys work even without your patch (I use iTerm2). Can you add some explanation on this?

**Comment by cesc-park** [comment]
I refer to this thread 
https://github.com/robbyrussell/oh-my-zsh/issues/3061#issuecomment-181801993
This setting worked for me instead of the default setting.
I use mac default Terminal 2.8.

**Comment by CptTZ** [comment]
Confirm solving this issue: <https://github.com/robbyrussell/oh-my-zsh/issues/3061#issuecomment-181801993>
I use XShell 5 on Windows, the server OS is Debian 9 x86_64.

**Comment by wookayin** [comment]
Merged. Thanks you guys!

**Comment by roachsinai** [comment]
Hey @cesc-park Why I still get the Home not work error https://github.com/robbyrussell/oh-my-zsh/issues/3061.

Have that issue when enabling vi-mode plugin! And seems "^[OH" not binding to beginning-of-line!

Here is my [omz_diagnostic_dump for Home and End key work wierd.](https://gist.github.com/roachsinai/e3888907e5ae098ce4571a10adc031bb)

**Pull request merged**
