### PR TITLE
Major update: Switch to zplug

### PR DESCRIPTION
**Pull request by wookayin**
[prezto](https://github.com/sorin-ionescu/prezto/) is out-dated and not maintained well. Let's switch to [zplug](https://github.com/zplug/zplug), a next-generation zsh plugin manager!

### TODO

- [x] Re-use prezto modules as much as we can
- [ ] Migrate all the custom configurations into zplug style
- [ ] Improve startup time (currently, ~2 sec?)
- [ ] Abandon prezto

### CODE REVIEW

**Comment by simnalamburt** [comment]
`zplug "modules/prompt", from:prezto` might be helpful

**Comment by wookayin** [comment]
Yeah, zplug >= 2.3.0 supports `from:prezto` predicates. Useful, but I find that there is a little discrepancy on prezto module loading. Currently investigating into this.

**Comment by wookayin** [comment]
A basic migration from prezto to zplug (to the extent that new zsh prompt is useable in any way) is done. The theme configuration (with asynchronous feature) is moved to [wookayin/pure](https://github.com/wookayin/pure).

Although it depends on prezto for now, I can take advantage of the power of zplug from now on!

**Comment by wookayin** [comment]
Some issues so far

* [ ] zsh completions are not sourced when zplug loads prezto (e.g. `z<tab>`)
* Sometimes, git status sync is broken

**Comment by wookayin** [comment]
Another problem: 

- [ ] root shell sucks (they complains about zcompinit ??!?)

**Comment by wookayin** [comment]
Judging it is now somewhat stablized and usable, merging into master --- yet there still might be some minor errors.

**Pull request merged**
